version: "3"
# TODO: test with '3.4'

services:
  issue.tests: # C:\Projects\Playground\testcontainers-dotnet-679>docker compose -p docker-compose.yml up issue.tests
    build:
      context: .
      dockerfile: Issue.Tests/Dockerfile
    entrypoint: dotnet
    command: test Issue.Tests/Issue.Tests.csproj
    #environment:
    #  - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #extra_hosts:
    #  - "host.docker.internal:192.168.65.2"